import type { Property } from './types';

const properties: Property[] = [
  {
    id: '1',
    title: 'Secluded Treehouse Getaway',
    location: 'Atlanta, Georgia',
    price: 350,
    rating: 4.98,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p1i1/1200/800',
      'https://picsum.photos/seed/p1i2/1200/800',
      'https://picsum.photos/seed/p1i3/1200/800',
      'https://picsum.photos/seed/p1i4/1200/800',
      'https://picsum.photos/seed/p1i5/1200/800',
    ],
    description:
      'A secluded and romantic treehouse for two. A little slice of heaven, a place to relax, and a perfect spot for a romantic getaway.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Free parking', 'Heating'],
    host: {
      name: 'Katie',
      avatar: 'https://picsum.photos/seed/h1/200',
    },
  },
  {
    id: '2',
    title: 'Modern Loft in Downtown',
    location: 'New York, New York',
    price: 220,
    rating: 4.85,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p2i1/1200/800',
      'https://picsum.photos/seed/p2i2/1200/800',
      'https://picsum.photos/seed/p2i3/1200/800',
      'https://picsum.photos/seed/p2i4/1200/800',
      'https://picsum.photos/seed/p2i5/1200/800',
    ],
    description:
      'Stylish and spacious loft in the heart of the city. Enjoy the amazing views and the vibrant neighborhood.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Elevator', 'Gym'],
    host: {
      name: 'Michael',
      avatar: 'https://picsum.photos/seed/h2/200',
    },
  },
  {
    id: '3',
    title: 'Cozy Beachfront Cottage',
    location: 'Malibu, California',
    price: 450,
    rating: 4.99,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    images: [
      'https://picsum.photos/seed/p3i1/1200/800',
      'https://picsum.photos/seed/p3i2/1200/800',
      'https://picsum.photos/seed/p3i3/1200/800',
      'https://picsum.photos/seed/p3i4/1200/800',
      'https://picsum.photos/seed/p3i5/1200/800',
    ],
    description: 'Wake up to the sound of waves in this beautiful beachfront cottage. Perfect for a family vacation or a serene retreat.',
    amenities: ['Wifi', 'Kitchen', 'Free parking', 'Beachfront', 'Patio'],
    host: {
      name: 'Jennifer',
      avatar: 'https://picsum.photos/seed/h3/200',
    },
  },
  {
    id: '4',
    title: 'Rustic Cabin in the Woods',
    location: 'Asheville, North Carolina',
    price: 180,
    rating: 4.91,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    images: [
      'https://picsum.photos/seed/p4i1/1200/800',
      'https://picsum.photos/seed/p4i2/1200/800',
      'https://picsum.photos/seed/p4i3/1200/800',
      'https://picsum.photos/seed/p4i4/1200/800',
      'https://picsum.photos/seed/p4i5/1200/800',
    ],
    description:
      'Escape to this charming cabin nestled in the Blue Ridge Mountains. Ideal for hiking enthusiasts and nature lovers.',
    amenities: ['Wifi', 'Kitchen', 'Free parking', 'Indoor fireplace', 'Pet friendly'],
    host: {
      name: 'David',
      avatar: 'https://picsum.photos/seed/h4/200',
    },
  },
  {
    id: '5',
    title: 'Chic Parisian Apartment',
    location: 'Paris, France',
    price: 300,
    rating: 4.88,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p5i1/1200/800',
      'https://picsum.photos/seed/p5i2/1200/800',
      'https://picsum.photos/seed/p5i3/1200/800',
      'https://picsum.photos/seed/p5i4/1200/800',
      'https://picsum.photos/seed/p5i5/1200/800',
    ],
    description:
      'Experience the magic of Paris from this elegant apartment. Located in a historic building with modern amenities.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Elevator', 'Washer'],
    host: {
      name: 'Sophie',
      avatar: 'https://picsum.photos/seed/h5/200',
    },
  },
  {
    id: '6',
    title: 'Desert Oasis with Pool',
    location: 'Scottsdale, Arizona',
    price: 550,
    rating: 5.0,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    images: [
      'https://picsum.photos/seed/p6i1/1200/800',
      'https://picsum.photos/seed/p6i2/1200/800',
      'https://picsum.photos/seed/p6i3/1200/800',
      'https://picsum.photos/seed/p6i4/1200/800',
      'https://picsum.photos/seed/p6i5/1200/800',
    ],
    description: 'A luxurious desert home with a stunning pool and outdoor living space. The ultimate retreat for relaxation and fun.',
    amenities: ['Wifi', 'Air conditioning', 'Pool', 'Hot tub', 'BBQ grill'],
    host: {
      name: 'Tom',
      avatar: 'https://picsum.photos/seed/h6/200',
    },
  },
  {
    id: '7',
    title: 'Mountain View Chalet',
    location: 'Whistler, British Columbia',
    price: 600,
    rating: 4.95,
    guests: 10,
    bedrooms: 5,
    beds: 7,
    baths: 4,
    images: [
      'https://picsum.photos/seed/p7i1/1200/800',
      'https://picsum.photos/seed/p7i2/1200/800',
      'https://picsum.photos/seed/p7i3/1200/800',
      'https://picsum.photos/seed/p7i4/1200/800',
      'https://picsum.photos/seed/p7i5/1200/800',
    ],
    description:
      'Breathtaking views await at this spacious chalet. Perfect for ski trips and mountain adventures with a large group.',
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Hot tub', 'Ski-in/Ski-out'],
    host: {
      name: 'Emily',
      avatar: 'https://picsum.photos/seed/h7/200',
    },
  },
  {
    id: '8',
    title: 'Historic Townhouse in Old Town',
    location: 'Kyoto, Japan',
    price: 280,
    rating: 4.93,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p8i1/1200/800',
      'https://picsum.photos/seed/p8i2/1200/800',
      'https://picsum.photos/seed/p8i3/1200/800',
      'https://picsum.photos/seed/p8i4/1200/800',
      'https://picsum.photos/seed/p8i5/1200/800',
    ],
    description: 'Stay in a beautifully restored machiya (traditional townhouse) in the heart of Gion, Kyoto’s most famous geisha district.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Tatami rooms', 'Garden'],
    host: {
      name: 'Yuki',
      avatar: 'https://picsum.photos/seed/h8/200',
    },
  },
  {
    id: '9',
    title: 'Minimalist Apartment in Tokyo',
    location: 'Shibuya, Tokyo',
    price: 190,
    rating: 4.89,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p9i1/1200/800',
      'https://picsum.photos/seed/p9i2/1200/800',
      'https://picsum.photos/seed/p9i3/1200/800',
      'https://picsum.photos/seed/p9i4/1200/800',
      'https://picsum.photos/seed/p9i5/1200/800',
    ],
    description: 'A sleek and modern apartment in the bustling heart of Shibuya. The perfect base for exploring the vibrant city of Tokyo.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Washer'],
    host: {
      name: 'Kenji',
      avatar: 'https://picsum.photos/seed/h9/200',
    },
  },
  {
    id: '10',
    title: 'Charming Cottage in the Cotswolds',
    location: 'Cotswolds, England',
    price: 250,
    rating: 4.97,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p10i1/1200/800',
      'https://picsum.photos/seed/p10i2/1200/800',
      'https://picsum.photos/seed/p10i3/1200/800',
      'https://picsum.photos/seed/p10i4/1200/800',
      'https://picsum.photos/seed/p10i5/1200/800',
    ],
    description: 'Experience the quintessential English countryside in this charming stone cottage. Features a beautiful garden and cozy fireplace.',
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Garden', 'Pet friendly'],
    host: {
      name: 'Eleanor',
      avatar: 'https://picsum.photos/seed/h10/200',
    },
  },
  {
    id: '11',
    title: 'Luxury Villa in Santorini',
    location: 'Oia, Santorini',
    price: 800,
    rating: 5.0,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    images: [
      'https://picsum.photos/seed/p11i1/1200/800',
      'https://picsum.photos/seed/p11i2/1200/800',
      'https://picsum.photos/seed/p11i3/1200/800',
      'https://picsum.photos/seed/p11i4/1200/800',
      'https://picsum.photos/seed/p11i5/1200/800',
    ],
    description: 'Indulge in luxury at this stunning villa with a private infinity pool and breathtaking caldera views. An unforgettable experience.',
    amenities: ['Wifi', 'Air conditioning', 'Pool', 'Hot tub', 'Beachfront'],
    host: {
      name: 'Dimitri',
      avatar: 'https://picsum.photos/seed/h11/200',
    },
  },
  {
    id: '12',
    title: 'Rustic Lodge in Jackson Hole',
    location: 'Jackson Hole, Wyoming',
    price: 480,
    rating: 4.96,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    images: [
      'https://picsum.photos/seed/p12i1/1200/800',
      'https://picsum.photos/seed/p12i2/1200/800',
      'https://picsum.photos/seed/p12i3/1200/800',
      'https://picsum.photos/seed/p12i4/1200/800',
      'https://picsum.photos/seed/p12i5/1200/800',
    ],
    description: 'A grand lodge with majestic mountain views. Close to Grand Teton National Park, it’s a paradise for outdoor adventurers.',
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Hot tub', 'BBQ grill'],
    host: {
      name: 'Jackson',
      avatar: 'https://picsum.photos/seed/h12/200',
    },
  },
  {
    id: '13',
    title: 'Vibrant Riad in Marrakech',
    location: 'Marrakech, Morocco',
    price: 180,
    rating: 4.92,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    images: [
      'https://picsum.photos/seed/p13i1/1200/800',
      'https://picsum.photos/seed/p13i2/1200/800',
      'https://picsum.photos/seed/p13i3/1200/800',
      'https://picsum.photos/seed/p13i4/1200/800',
      'https://picsum.photos/seed/p13i5/1200/800',
    ],
    description: 'Immerse yourself in Moroccan culture in this traditional Riad. Features a stunning courtyard pool and rooftop terrace.',
    amenities: ['Wifi', 'Air conditioning', 'Pool', 'Patio', 'Washer'],
    host: {
      name: 'Fatima',
      avatar: 'https://picsum.photos/seed/h13/200',
    },
  },
  {
    id: '14',
    title: 'Modern Penthouse in Sydney',
    location: 'Sydney, Australia',
    price: 400,
    rating: 4.87,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    images: [
      'https://picsum.photos/seed/p14i1/1200/800',
      'https://picsum.photos/seed/p14i2/1200/800',
      'https://picsum.photos/seed/p14i3/1200/800',
      'https://picsum.photos/seed/p14i4/1200/800',
      'https://picsum.photos/seed/p14i5/1200/800',
    ],
    description: 'A sleek penthouse offering panoramic views of Sydney Harbour. Features a modern design and a spacious balcony.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Elevator', 'Gym'],
    host: {
      name: 'Chloe',
      avatar: 'https://picsum.photos/seed/h14/200',
    },
  },
  {
    id: '15',
    title: 'Lakeside Cabin in Finland',
    location: 'Lapland, Finland',
    price: 320,
    rating: 4.99,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p15i1/1200/800',
      'https://picsum.photos/seed/p15i2/1200/800',
      'https://picsum.photos/seed/p15i3/1200/800',
      'https://picsum.photos/seed/p15i4/1200/800',
      'https://picsum.photos/seed/p15i5/1200/800',
    ],
    description: 'A cozy cabin on the shore of a pristine lake. Perfect for viewing the Northern Lights and enjoying a traditional Finnish sauna.',
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Heating', 'Pet friendly'],
    host: {
      name: 'Aino',
      avatar: 'https://picsum.photos/seed/h15/200',
    },
  },
  {
    id: '16',
    title: 'Historic Brownstone in Brooklyn',
    location: 'Brooklyn, New York',
    price: 260,
    rating: 4.84,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    images: [
      'https://picsum.photos/seed/p16i1/1200/800',
      'https://picsum.photos/seed/p16i2/1200/800',
      'https://picsum.photos/seed/p16i3/1200/800',
      'https://picsum.photos/seed/p16i4/1200/800',
      'https://picsum.photos/seed/p16i5/1200/800',
    ],
    description: 'Live like a local in a classic Brooklyn brownstone. This charming apartment combines historic details with modern comfort.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Washer', 'Patio'],
    host: {
      name: 'Sarah',
      avatar: 'https://picsum.photos/seed/h16/200',
    },
  },
  {
    id: '17',
    title: 'Eco-Friendly Dome in Costa Rica',
    location: 'La Fortuna, Costa Rica',
    price: 210,
    rating: 4.94,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p17i1/1200/800',
      'https://picsum.photos/seed/p17i2/1200/800',
      'https://picsum.photos/seed/p17i3/1200/800',
      'https://picsum.photos/seed/p17i4/1200/800',
      'https://picsum.photos/seed/p17i5/1200/800',
    ],
    description: 'A unique stay in a geodesic dome surrounded by lush rainforest. Wake up to the sounds of nature and enjoy stunning volcano views.',
    amenities: ['Wifi', 'Kitchen', 'Free parking', 'Garden'],
    host: {
      name: 'Carlos',
      avatar: 'https://picsum.photos/seed/h17/200',
    },
  },
  {
    id: '18',
    title: 'Traditional Trullo in Alberobello',
    location: 'Alberobello, Italy',
    price: 150,
    rating: 4.98,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p18i1/1200/800',
      'https://picsum.photos/seed/p18i2/1200/800',
      'https://picsum.photos/seed/p18i3/1200/800',
      'https://picsum.photos/seed/p18i4/1200/800',
      'https://picsum.photos/seed/p18i5/1200/800',
    ],
    description: 'Stay in a historic Trullo, a traditional Apulian dry stone hut with a conical roof. A one-of-a-kind fairytale experience.',
    amenities: ['Wifi', 'Air conditioning', 'Kitchen', 'Free parking', 'Patio'],
    host: {
      name: 'Giulia',
      avatar: 'https://picsum.photos/seed/h18/200',
    },
  },
  {
    id: '19',
    title: 'Houseboat on Amsterdam Canal',
    location: 'Amsterdam, Netherlands',
    price: 230,
    rating: 4.86,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    images: [
      'https://picsum.photos/seed/p19i1/1200/800',
      'https://picsum.photos/seed/p19i2/1200/800',
      'https://picsum.photos/seed/p19i3/1200/800',
      'https://picsum.photos/seed/p19i4/1200/800',
      'https://picsum.photos/seed/p19i5/1200/800',
    ],
    description: 'Experience Amsterdam from a unique perspective on a cozy and modern houseboat. Located on a quiet canal, yet close to the city center.',
    amenities: ['Wifi', 'Kitchen', 'Heating', 'Patio'],
    host: {
      name: 'Lars',
      avatar: 'https://picsum.photos/seed/h19/200',
    },
  },
  {
    id: '20',
    title: 'Penthouse with City Views in Dubai',
    location: 'Dubai, UAE',
    price: 650,
    rating: 4.9,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    images: [
      'https://picsum.photos/seed/p20i1/1200/800',
      'https://picsum.photos/seed/p20i2/1200/800',
      'https://picsum.photos/seed/p20i3/1200/800',
      'https://picsum.photos/seed/p20i4/1200/800',
      'https://picsum.photos/seed/p20i5/1200/800',
    ],
    description: 'A lavish penthouse in the sky with breathtaking views of the Dubai skyline. Enjoy luxury amenities including a rooftop pool and gym.',
    amenities: ['Wifi', 'Air conditioning', 'Pool', 'Gym', 'Elevator'],
    host: {
      name: 'Ahmed',
      avatar: 'https://picsum.photos/seed/h20/200',
    },
  },
];

export function getProperties() {
  return properties;
}

export function getPropertyById(id: string) {
  return properties.find((p) => p.id === id);
}
